# Generated by Django 5.0 on 2023-12-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_is_approved_alter_postmodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images/')),
            ],
        ),
        migrations.AddField(
            model_name='postmodel',
            name='sections',
            field=models.ManyToManyField(to='blog.postsection'),
        ),
    ]
