# Generated by Django 5.0 on 2023-12-11 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postsection_postmodel_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsection',
            name='post_model',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='post_sections', to='blog.postmodel'),
            preserve_default=False,
        ),
    ]
