# Generated by Django 5.0 on 2023-12-11 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postsection_post_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default='default_post.png', upload_to='post_pictures/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='postsection',
            name='image',
            field=models.ImageField(upload_to='post_pictures/'),
        ),
    ]
