# Generated by Django 5.0 on 2023-12-12 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_postsection_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsection',
            name='section_image',
            field=models.ImageField(upload_to='post_pictures/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
