# Generated by Django 5.0 on 2023-12-12 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_section_content_postsection_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postsection',
            options={},
        ),
        migrations.RemoveField(
            model_name='postsection',
            name='post_model',
        ),
        migrations.AlterField(
            model_name='postsection',
            name='image',
            field=models.ImageField(default='default_post.png', upload_to='post_pictures', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
