# Generated by Django 5.0 on 2023-12-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_postsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsection',
            name='post_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.postmodel'),
        ),
    ]
