# Generated by Django 5.0 on 2023-12-19 11:12

import ckeditor.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_postsection_post_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='editor',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
