# Generated by Django 5.0 on 2023-12-19 11:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_postmodel_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='editor',
        ),
    ]
