# Generated by Django 5.0 on 2023-12-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_richtext_remove_postmodel_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RichText',
        ),
    ]
